Update
SafeerAhmFarooqi/A1-Jewellers pull request #1
Opened 2022-07-16 16:41 UTC by SafeerAhmFarooqi

2022-07-16 16:46 UTC, amanank commented on database/migrations/2022_07_16_130906_create_tasks_table.php
> +            $table->string('name')->nullable();
You have a validation rule restricting length to 255 but haven't set it here?

2022-07-16 16:47 UTC, amanank commented on app/Http/Controllers/TaskController.php
> +        $tasks = Task::orderBy('created_at', 'asc')->get();
Queries should be in Model not in controller

2022-07-16 16:48 UTC, amanank commented on app/Http/Controllers/TaskController.php
> +            'required'=>':attribute Required',
what's this?

2022-07-16 16:50 UTC, amanank requested changes
Good overall few minor changes required

2022-07-16 18:32 UTC, amanank commented on resources/views/task.blade.php
> +                          <input type="text" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" name="task">
Why name this field `task` why not `name`?

2022-07-17 19:03 UTC, SafeerAhmFarooqi commented on database/migrations/2022_07_16_130906_create_tasks_table.php
> +            $table->string('name')->nullable();
I just let it open because in future if we have to increase the length then it should not be a problem.

2022-07-17 19:06 UTC, SafeerAhmFarooqi commented on resources/views/task.blade.php
> +                          <input type="text" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" name="task">
Ok I will change it to name.

2022-07-17 19:13 UTC, merged

2022-07-18 10:20 UTC, amanank commented on database/migrations/2022_07_16_130906_create_tasks_table.php
> +            $table->string('name')->nullable();
This is not a good reason, when we need to increase length in future we will update both the validation rule and db schema

2022-07-18 10:28 UTC, SafeerAhmFarooqi commented on database/migrations/2022_07_16_130906_create_tasks_table.php
> +            $table->string('name')->nullable();
ok I will change it.

2022-07-18 11:42 UTC, SafeerAhmFarooqi commented on app/Http/Controllers/TaskController.php
> +        $tasks = Task::orderBy('created_at', 'asc')->get();
I have shifted queries to the model.